// <auto-generated />
using System;
using FunDateIdeas.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FunDateIdeas.DAL.Data.Migrations
{
    [DbContext(typeof(FunDateIdeasDbContext))]
    [Migration("20200921202344_AddedKeysToDateIdeaLikesTable")]
    partial class AddedKeysToDateIdeaLikesTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FunDateIdeas.DAL.Data.DateIdea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DateIdeas");
                });

            modelBuilder.Entity("FunDateIdeas.DAL.Data.DateIdeaLike", b =>
                {
                    b.Property<Guid>("DateIdeaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DateIdeaId", "UserId");

                    b.ToTable("DateIdeaLikes");
                });
#pragma warning restore 612, 618
        }
    }
}
